[
    {
        "assignee": null, 
        "assignees": [], 
        "author_association": "NONE", 
        "body": "Olá, o erro ocorre ao tentar baixar as dependências do projeto(pip install -r requirements.txt). Pelo que constatei, o erro se dá quando tenta baixar o cryptography==0.5.4\n\nDownloading/unpacking cryptography==0.5.4 (from -r requirements.txt (line 5))\n  Downloading cryptography-0.5.4.tar.gz (320kB): 320kB downloaded\n  Running setup.py (path:/tmp/pip-build-yLZvFh/cryptography/setup.py) egg_info for package cryptography\n\n```\nbuilding '_Cryptography_cffi_684bb40axf342507b' extension\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.c -o /tmp/pip-build-yLZvFh/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.o\ncryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.c:2:20: fatal error: Python.h: Arquivo ou diretório não encontrado\ncompilation terminated.\nTraceback (most recent call last):\n  File \"<string>\", line 17, in <module>\n  File \"/tmp/pip-build-yLZvFh/cryptography/setup.py\", line 174, in <module>\n    \"test\": PyTest,\n  File \"/usr/lib/python2.7/distutils/core.py\", line 151, in setup\n    dist.run_commands()\n  File \"/usr/lib/python2.7/distutils/dist.py\", line 953, in run_commands\n    self.run_command(cmd)\n  File \"/usr/lib/python2.7/distutils/dist.py\", line 972, in run_command\n    cmd_obj.run()\n  File \"<string>\", line 15, in replacement_run\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py\", line 207, in find_sources\n    mm.run()\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py\", line 291, in run\n    self.add_defaults()\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py\", line 320, in add_defaults\n    sdist.add_defaults(self)\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/sdist.py\", line 118, in add_defaults\n    build_py = self.get_finalized_command('build_py')\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 312, in get_finalized_command\n    cmd_obj.ensure_finalized()\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 109, in ensure_finalized\n    self.finalize_options()\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py\", line 28, in finalize_options\n    orig.build_py.finalize_options(self)\n  File \"/usr/lib/python2.7/distutils/command/build_py.py\", line 46, in finalize_options\n    ('force', 'force'))\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 298, in set_undefined_options\n    src_cmd_obj.ensure_finalized()\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 109, in ensure_finalized\n    self.finalize_options()\n  File \"/tmp/pip-build-yLZvFh/cryptography/setup.py\", line 88, in finalize_options\n    self.distribution.ext_modules = get_ext_modules()\n  File \"/tmp/pip-build-yLZvFh/cryptography/setup.py\", line 65, in get_ext_modules\n    from cryptography.hazmat.primitives import constant_time, padding\n  File \"cryptography/hazmat/primitives/constant_time.py\", line 54, in <module>\n    ext_package=\"cryptography\",\n  File \"/usr/lib/python2.7/dist-packages/cffi/api.py\", line 373, in verify\n    lib = self.verifier.load_library()\n  File \"/usr/lib/python2.7/dist-packages/cffi/verifier.py\", line 96, in load_library\n    self._compile_module()\n  File \"/usr/lib/python2.7/dist-packages/cffi/verifier.py\", line 192, in _compile_module\n    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())\n  File \"/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py\", line 38, in compile\n    outputfilename = _build(tmpdir, ext)\n  File \"/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py\", line 65, in _build\n    raise VerificationError('%s: %s' % (e.__class__.__name__, e))\ncffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\nComplete output from command python setup.py egg_info:\nrunning egg_info\n```\n\ncreating pip-egg-info/cryptography.egg-info\n\nwriting requirements to pip-egg-info/cryptography.egg-info/requires.txt\n\nwriting pip-egg-info/cryptography.egg-info/PKG-INFO\n\nwriting top-level names to pip-egg-info/cryptography.egg-info/top_level.txt\n\nwriting dependency_links to pip-egg-info/cryptography.egg-info/dependency_links.txt\n\nwriting manifest file 'pip-egg-info/cryptography.egg-info/SOURCES.txt'\n\nwarning: manifest_maker: standard file '-c' not found\n\nrunning build_ext\n\nbuilding '_Cryptography_cffi_684bb40axf342507b' extension\n\ncreating /tmp/pip-build-yLZvFh/cryptography/cryptography/hazmat/primitives/**pycache**/cryptography\n\ncreating /tmp/pip-build-yLZvFh/cryptography/cryptography/hazmat/primitives/**pycache**/cryptography/hazmat\n\ncreating /tmp/pip-build-yLZvFh/cryptography/cryptography/hazmat/primitives/**pycache**/cryptography/hazmat/primitives\n\ncreating /tmp/pip-build-yLZvFh/cryptography/cryptography/hazmat/primitives/**pycache**/cryptography/hazmat/primitives/**pycache**\n\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cryptography/hazmat/primitives/**pycache**/_Cryptography_cffi_684bb40axf342507b.c -o /tmp/pip-build-yLZvFh/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/**pycache**/_Cryptography_cffi_684bb40axf342507b.o\n\ncryptography/hazmat/primitives/**pycache**/_Cryptography_cffi_684bb40axf342507b.c:2:20: fatal error: Python.h: Arquivo ou diretório não encontrado\n\ncompilation terminated.\n\nTraceback (most recent call last):\n\n  File \"<string>\", line 17, in <module>\n\n  File \"/tmp/pip-build-yLZvFh/cryptography/setup.py\", line 174, in <module>\n\n```\n\"test\": PyTest,\n```\n\n  File \"/usr/lib/python2.7/distutils/core.py\", line 151, in setup\n\n```\ndist.run_commands()\n```\n\n  File \"/usr/lib/python2.7/distutils/dist.py\", line 953, in run_commands\n\n```\nself.run_command(cmd)\n```\n\n  File \"/usr/lib/python2.7/distutils/dist.py\", line 972, in run_command\n\n```\ncmd_obj.run()\n```\n\n  File \"<string>\", line 15, in replacement_run\n\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py\", line 207, in find_sources\n\n```\nmm.run()\n```\n\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py\", line 291, in run\n\n```\nself.add_defaults()\n```\n\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py\", line 320, in add_defaults\n\n```\nsdist.add_defaults(self)\n```\n\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/sdist.py\", line 118, in add_defaults\n\n```\nbuild_py = self.get_finalized_command('build_py')\n```\n\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 312, in get_finalized_command\n\n```\ncmd_obj.ensure_finalized()\n```\n\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 109, in ensure_finalized\n\n```\nself.finalize_options()\n```\n\n  File \"/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py\", line 28, in finalize_options\n\n```\norig.build_py.finalize_options(self)\n```\n\n  File \"/usr/lib/python2.7/distutils/command/build_py.py\", line 46, in finalize_options\n\n```\n('force', 'force'))\n```\n\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 298, in set_undefined_options\n\n```\nsrc_cmd_obj.ensure_finalized()\n```\n\n  File \"/usr/lib/python2.7/distutils/cmd.py\", line 109, in ensure_finalized\n\n```\nself.finalize_options()\n```\n\n  File \"/tmp/pip-build-yLZvFh/cryptography/setup.py\", line 88, in finalize_options\n\n```\nself.distribution.ext_modules = get_ext_modules()\n```\n\n  File \"/tmp/pip-build-yLZvFh/cryptography/setup.py\", line 65, in get_ext_modules\n\n```\nfrom cryptography.hazmat.primitives import constant_time, padding\n```\n\n  File \"cryptography/hazmat/primitives/constant_time.py\", line 54, in <module>\n\n```\next_package=\"cryptography\",\n```\n\n  File \"/usr/lib/python2.7/dist-packages/cffi/api.py\", line 373, in verify\n\n```\nlib = self.verifier.load_library()\n```\n\n  File \"/usr/lib/python2.7/dist-packages/cffi/verifier.py\", line 96, in load_library\n\n```\nself._compile_module()\n```\n\n  File \"/usr/lib/python2.7/dist-packages/cffi/verifier.py\", line 192, in _compile_module\n\n```\noutputfilename = ffiplatform.compile(tmpdir, self.get_extension())\n```\n\n  File \"/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py\", line 38, in compile\n\n```\noutputfilename = _build(tmpdir, ext)\n```\n\n  File \"/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py\", line 65, in _build\n\n```\nraise VerificationError('%s: %s' % (e.__class__.__name__, e))\n```\n\ncffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n\n---\n\nCleaning up...\nCommand python setup.py egg_info failed with error code 1 in /tmp/pip-build-yLZvFh/cryptography\nTraceback (most recent call last):\n  File \"/usr/bin/pip\", line 9, in <module>\n    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()\n  File \"/usr/lib/python2.7/dist-packages/pip/**init**.py\", line 248, in main\n    return command.main(cmd_args)\n  File \"/usr/lib/python2.7/dist-packages/pip/basecommand.py\", line 161, in main\n    text = '\\n'.join(complete_log)\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 131: ordinal not in range(128)\n", 
        "closed_at": "2016-05-17T21:10:59Z", 
        "comments": 0, 
        "comments_url": "https://api.github.com/repos/vitorbaptista/dados-abertos-camara.gov.br/issues/1/comments", 
        "created_at": "2016-02-24T19:57:49Z", 
        "events_url": "https://api.github.com/repos/vitorbaptista/dados-abertos-camara.gov.br/issues/1/events", 
        "html_url": "https://github.com/vitorbaptista/dados-abertos-camara.gov.br/issues/1", 
        "id": 136170383, 
        "labels": [], 
        "labels_url": "https://api.github.com/repos/vitorbaptista/dados-abertos-camara.gov.br/issues/1/labels{/name}", 
        "locked": false, 
        "milestone": null, 
        "node_id": "MDU6SXNzdWUxMzYxNzAzODM=", 
        "number": 1, 
        "repository_url": "https://api.github.com/repos/vitorbaptista/dados-abertos-camara.gov.br", 
        "state": "closed", 
        "title": "Erro ao baixar as dependências do projeto", 
        "updated_at": "2016-05-17T21:10:59Z", 
        "url": "https://api.github.com/repos/vitorbaptista/dados-abertos-camara.gov.br/issues/1", 
        "user": {
            "avatar_url": "https://avatars3.githubusercontent.com/u/7468564?v=4", 
            "events_url": "https://api.github.com/users/emerson-diego/events{/privacy}", 
            "followers_url": "https://api.github.com/users/emerson-diego/followers", 
            "following_url": "https://api.github.com/users/emerson-diego/following{/other_user}", 
            "gists_url": "https://api.github.com/users/emerson-diego/gists{/gist_id}", 
            "gravatar_id": "", 
            "html_url": "https://github.com/emerson-diego", 
            "id": 7468564, 
            "login": "emerson-diego", 
            "node_id": "MDQ6VXNlcjc0Njg1NjQ=", 
            "organizations_url": "https://api.github.com/users/emerson-diego/orgs", 
            "received_events_url": "https://api.github.com/users/emerson-diego/received_events", 
            "repos_url": "https://api.github.com/users/emerson-diego/repos", 
            "site_admin": false, 
            "starred_url": "https://api.github.com/users/emerson-diego/starred{/owner}{/repo}", 
            "subscriptions_url": "https://api.github.com/users/emerson-diego/subscriptions", 
            "type": "User", 
            "url": "https://api.github.com/users/emerson-diego"
        }
    }
]